id = "cache_ttl"
weight = 1
type = "snippet"
title = "Cache using fetch"
description = "Determine how/if to cache a resource by setting TTLs, custom cache keys, and cache headers in a fetch [`request`](/workers/reference/apis/request/) to gain granular control of browsers' and Cloudflare's caches for even your dynamic assets like caching HTML. "

[demos.main]
text = "Demo"
url = "https://cloudflareworkers.com/#8dd3e29985701b05e43b4dd74c387b74:https://example.com/"
tags = [ "Middleware", "Enterprise" ]
