id = "modify_req_props"
weight = 1
type = "snippet"
title = "Modify Request Property"
description = "Recommended practice for forming a [request](/workers/reference/apis/request) based off the incoming request. First, takes in the incoming request then modifies specific properties like POST `body`, `redirect`, and the Cloudflare specific property `cf` and runs the fetch."
share_url = "/templates/snippets/modify_req_props"

[demos.main]
text = "Demo"
url = "https://cloudflareworkers.com/#27b91145f66b6cfce1b3190ed7ba0bc5:https://example.com"
tags = [ "Middleware" ]
